version: "3.7"
services:
  webserver:
    build:
      args:
        user: bilalhalawaty
        uid: 7474
      context: ./
      dockerfile: Dockerfile
    image: dayra
    container_name: dayra
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - dayra

  db:
    image: mysql:5.7
    container_name: dayra-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: dayra
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    ports:
      - 4366:3306
    networks:
      - dayra

  nginx:
    image: nginx:alpine
    container_name: dayra-nginx
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./sites:/etc/nginx/conf.d/
    networks:
      - dayra

networks:
  dayra:
    driver: bridge
